export const FECTH_BLOG_REQUEST = "FECTH_BLOG_REQUEST";
export const FECTH_BLOG_SUCCESS = "FECTH_BLOG_SUCCESS";
export const FECTH_BLOG_FAILED = "FECTH_BLOG_FAILED";

export const SEARCH_BLOG_REQUEST = "SEARCH_BLOG_REQUEST";
export const SEARCH_BLOG_SUCCESS = "SEARCH_BLOG_SUCCESS";
export const SEARCH_BLOG_FAILED = "SEARCH_BLOG_FAILED";