export const NEWSLETTER_SUBSCRIPTION_REQUEST = "NEWSLETTER_SUBSCRIPTION_REQUEST";
export const NEWSLETTER_SUBSCRIPTION_SUCCESS = "NEWSLETTER_SUBSCRIPTION_SUCCESS";
export const NEWSLETTER_SUBSCRIPTION_FAILED = "NEWSLETTER_SUBSCRIPTION_FAILED";